<?php

/**
 * Plyr HTML5 Media Player module for ProcessWire
 *
 * ProcessWire 2.5.5+ 
 * Copyright (C) 2015 by Orkan Alat 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * https://github.com/tsdtsdtsd/PlyrMediaPlayer
 * https://plyr.io/
 */
class MarkupPlyrMediaPlayer extends WireData implements Module, ConfigurableModule 
{

    /**
     * Keeps track if a player was requested in this loop
     * @var boolean
     */
    protected $_playerRequested = false;

    /**
     * The default values of module configuration
     * @var array
     */
    protected static $defaultConfigData = array(
        'automaticMode' => 1,
        'useCdn' => 1,
        // 'forceFallbackFiles' => 0,
        'cssPath' => 'plyr.css',
        'jsPath' => 'plyr.js',
        'svgPath' => 'sprite.svg',
    ); 

    /**
     * Returns module info array
     *
     * @todo  Check info posibilities (e.g. requirement definitions)
     * @return array
     */
    public static function getModuleInfo() 
    {
        return array(

            'title' => 'Plyr Media Player', 
            'version' => '0.1.2', 
            'summary' => 'This module adds the Plyr HTML5 Media Player (https://plyr.io/) to ProcessWire',
            'href' => 'https://github.com/tsdtsdtsd/PlyrMediaPlayer',
            'singular' => true, 
            'autoload' => true,
            'icon' => 'youtube-play'
        );
    }

    /**
     * Set the default config data
     *
     */
    public function __construct() {
        foreach(self::$defaultConfigData as $key => $value) {
            $this->set($key, $value); 
        }
    }

    public function ready() 
    {
        if($this->page->template == 'admin') return;

        $config = wire('modules')->getModuleConfigData($this);
        if(empty($config['automaticMode'])) return;

        $this->addHookAfter('Page::render', $this, '_addPlyrToOutput'); 
    }

    protected function _addPlyrToOutput($event) 
    {
        if(!$this->_playerRequested) return;

        // $page = $event->object; 
        // $config = wire('modules')->getModuleConfigData($this);
        $outputHead = $this->renderHtmlHead();
        $outputFooter= $this->renderHtmlFooter();

        $event->return = str_replace("</head>", $outputHead . '</head>', $event->return); 
        $event->return = str_replace("</body>", $outputFooter . '</body>', $event->return); 
    }

    /**
     * Returns rendered HTML of a video player
     *
     * @todo   Refactor. Maybe I can use the ProcessWire template rendering?
     * @param  array  $captions The movie captions
     * @return string
     */
    public function renderVideoPlayer($poster, $mp4, $webm, $captions = array())
    {
        $this->_playerRequested = true;
        
        return '<div class="player">
                    <video poster="' . $poster . '" controls crossorigin>
                        <!-- Video files -->
                        <source src="' . $mp4 . '" type="video/mp4">
                        <source src="' . $webm . '" type="video/webm">

                        <!-- Text track file 
                        <track kind="captions" label="" src="" srclang="" default>-->

                        <!-- Fallback for browsers that don\'t support the <video> element -->
                        <a href="' . $mp4 . '">Download</a>
                    </video>
                </div>';
    }

    /**
     * Returns rendered HTML of an audio player
     *
     * @todo   Refactor. Maybe I can use the ProcessWire template rendering?
     * @param  string  $mp3Path     Path to mp3 file
     * @param  string  $oggPath     Path to ogg file (optional)
     * @return string
     */
    public function renderAudioPlayer($mp3Path, $oggPath = null)
    {
        $this->_playerRequested = true;

        // https://cdn.selz.com/plyr/1.0/logistics-96-sample.mp3
        // https://cdn.selz.com/plyr/1.0/logistics-96-sample.ogg
        $rendered = '<div class="player">
                        <audio controls>
                            <!-- Audio files -->
                            <source src="' . $mp3Path . '" type="audio/mp3">';

        $rendered .= !empty($oggPath) ? '<source src="' . $oggPath . '" type="audio/ogg">' : '';

        $rendered .= '
                            <!-- Fallback for browsers that don\'t support the <audio> element -->
                            <a href="' . $mp3Path . '">Download</a>
                        </audio>
                    </div>';

        return $rendered;
    }

    /**
     * Returns rendered HTML of a youtube player
     *
     * @todo   Refactor. Maybe I can use the ProcessWire template rendering?
     * @param  string  $videoId     The YouTube video ID
     * @return string
     */
    public function renderYoutubePlayer($videoId)
    {
        $this->_playerRequested = true;
        
        // L1h9xxCU20g
        return '<div class="player">
                    <div data-video-id="' . $videoId . '" data-type="youtube"></div>
                </div>';
    }

    /**
     * Returns code which is required in the HTML head
     *
     * Contains CSS stylesheet
     * 
     * @return string
     */
    public function renderHtmlHead()
    {
        $config = wire('modules')->getModuleConfigData($this);

        if($config['useCdn']) {
            $cssPath = 'https://cdn.plyr.io/1.3.5/plyr.css';
        }
        elseif($config['cssPath']) {
            $cssPath = $config['cssPath'];
        }

        if(!empty($cssPath)) {
            return '<link rel="stylesheet" href="' . $cssPath . '">';
        }
    }

    /**
     * Returns code which is required in the HTML Footer
     *
     * Contains AJAX request for the SVG image
     * Contains Plyr library include
     * Contains call to plyr.setup()
     * 
     * @return string
     */
    public function renderHtmlFooter()
    {
        return '<script>
                (function(d, p){
                    var a = new XMLHttpRequest(),
                        b = d.body;
                    a.open("GET", p, true);
                    a.send();
                    a.onload = function(){
                        var c = d.createElement("div");
                        c.style.display = "none";
                        c.innerHTML = a.responseText;
                        b.insertBefore(c, b.childNodes[0]);
                    }
                })(document, "https://cdn.plyr.io/1.3.5/sprite.svg");
                </script>

                <script src="https://cdn.plyr.io/1.3.5/plyr.js"></script>
                <script>plyr.setup();</script>';
    }

    public function ___install() 
    {
    }

    public function ___uninstall() 
    {
    }
    
    /**
     * Provide fields for configuring this module
     *
     */
    static public function getModuleConfigInputfields(array $data) {

        foreach(self::$defaultConfigData as $key => $value) {
            if(!isset($data[$key])) $data[$key] = $value; 
        }

        $inputfields = new InputfieldWrapper();

        $f = wire('modules')->get("InputfieldCheckbox");
        $f->attr('name', 'automaticMode');
        $f->attr('checked', $data['automaticMode'] ? 'checked' : '' );
        $f->label = "Automatic Mode";
        $f->description = __("If enabled, this option will automaticaly add all needed resources into your pages output.");
        $f->notes = __("The resources will only be loaded, if your page renders a player.");
        $inputfields->add($f);

        $fieldset = wire('modules')->get("InputfieldFieldset");
        $fieldset->label = "Resources";
        $fieldset->collapsed = Inputfield::collapsedNo;
        $inputfields->add($fieldset);

        $f = wire('modules')->get("InputfieldCheckbox");
        $f->attr('name', 'useCdn');
        $f->label = "Use CDN";
        $f->description = __("Use the official Plyr CDN (Content Delivery Network) for resources?");
        $f->notes = __("Only in automatic mode: The resources will only be loaded, if your page renders a player.");
        $f->attr('checked', $data['useCdn'] ? 'checked' : '' );
        $f->columnWidth = 50;
        $fieldset->add($f);

        // $f = wire('modules')->get("InputfieldCheckbox");
        // $f->attr('name', 'forceFallbackFiles');
        // $f->label = "Fallback to local files";
        // $f->description = __("Always use the local resource files as a fallback location of the CDN.");
        // $f->notes = __("Only in automatic mode: The resources will only be loaded, if your page renders a player.");
        // $f->attr('checked', $data['forceFallbackFiles'] ? 'checked' : '' );
        // $f->columnWidth = 50;
        // $fieldset->add($f);

        $f = wire('modules')->get('InputfieldText');
        $f->attr('name', 'cssPath');
        $f->attr('value', $data['cssPath']);
        $f->label = __('Path to CSS file');
        $f->placeholder = 'plyr.css';
        $f->showIf = 'useCdn=0';
        $f->description = "Path to your CSS file, required to style the players.";
        $fieldset->add($f);

        $f = wire('modules')->get('InputfieldText');
        $f->attr('name', 'jsPath');
        $f->attr('value', $data['jsPath']);
        $f->label = __('Path to the Plyr javascript library.');
        $f->placeholder = 'plyr.js';
        $f->showIf = 'useCdn=0';
        $f->description = "Path to the Plyr javascript library, required for the functionality.";
        $fieldset->add($f);

        $f = wire('modules')->get('InputfieldText');
        $f->attr('name', 'svgPath');
        $f->attr('value', $data['svgPath']);
        $f->label = __('Path to SVG file');
        $f->placeholder = 'sprite.svg';
        $f->showIf = 'useCdn=0';
        $f->description = "Path to your SVG sprite image file, required to style the players.";
        $fieldset->add($f);

        // $f = wire('modules')->get('InputfieldText');
        // $f->attr('name', 'plyrOptions');
        // $f->attr('value', $data['copyright']);
        // $f->label = "Plyr Player Options";
        // $f->description = "For now, JSON-formated string";
        // $inputfields->add($f);

        return $inputfields;
    }
}